import { getFirestore } from "../../lib/firestore.js";
import type { Request, Response } from "express";

export default async function handler(req: any, res: any) {
  if (req.method === 'OPTIONS') return res.status(200).end();

  // Validate Authorization secret for Vercel Cron or GitHub trigger
  const authHeader = req.headers.authorization;
  const cronSecret = process.env.CRON_SECRET || process.env.GOOGLE_CLOUD_PROJECT_ID;
  
  if (cronSecret && authHeader !== `Bearer ${cronSecret}` && req.query.secret !== cronSecret) {
    console.warn("[Cron AutoSnapshot] Unauthorized access attempt.");
  }

  const db = getFirestore();
  if (!db) {
    return res.status(500).json({ error: "Firestore unavailable. Check GOOGLE_CLOUD_* env variables." });
  }

  try {
    // 1. Fetch current event from FPL API
    const fplRes = await fetch('https://fantasy.premierleague.com/api/bootstrap-static/', {
      headers: { 'User-Agent': 'Mozilla/5.0' }
    });
    const data = await fplRes.json();
    const nextEvent = data.events?.find((e: any) => e.is_next) ??
                      data.events?.find((e: any) => new Date(e.deadline_time) > new Date());
    
    const gwId = nextEvent?.id || 1;

    // 2. Query registered team IDs
    const snapshotDocs = await db.collection('user_snapshots').get();
    const teamIdList: string[] = ['532002', '1884833', '3097103', '902458', '904491', '601847', '906422', '1921923', '1924837', '600311', '3274378', '9291073', '903137'];

    snapshotDocs.forEach(doc => {
      if (doc.id.startsWith('team_')) {
        const tid = doc.id.replace('team_', '').trim();
        if (tid && !teamIdList.includes(tid)) {
          teamIdList.push(tid);
        }
      }
    });

    const fuels = ['fplform', 'native', 'eye-test'];
    const modes = ['safe', 'aggressive', 'value'];
    const scenarios = ['quant', 'template'];

    let count = 0;

    for (const tid of teamIdList) {
      const docKey = `team_${tid}`;
      const docRef = db.collection('user_snapshots').doc(docKey);
      const docSnap = await docRef.get();
      const existingHistory = docSnap.exists ? (docSnap.data()?.history || {}) : {};
      const newGwHistory = { ...(existingHistory[gwId] || {}) };

      for (const fuel of fuels) {
        for (const scenario of scenarios) {
          for (const mode of modes) {
            const snapshotKey = `${fuel}_${scenario}_${mode}`;
            const snapshotItem = {
              key: snapshotKey,
              fuel,
              scenario,
              riskMode: mode,
              fuelLabel: fuel === 'eye-test' ? 'Eye Test' : fuel === 'native' ? 'Native FPL' : 'FPLForm',
              scenarioLabel: scenario === 'quant' ? 'Quant Optimal' : 'Risky Template Shield',
              riskLabel: mode.toUpperCase(),
              autoGenerated: true,
              timestamp: Date.now()
            };
            newGwHistory[snapshotKey] = snapshotItem;
            newGwHistory[mode] = snapshotItem;
          }
        }
      }

      existingHistory[gwId] = newGwHistory;
      await docRef.set({
        history: existingHistory,
        season: '2026/27',
        lastAutoSnapshotAt: new Date()
      }, { merge: true });
      count++;
    }

    return res.json({ success: true, message: `Auto-snapshot completed for GW${gwId}`, snapshottedCount: count, totalTeams: teamIdList.length });
  } catch (error: any) {
    console.error("[Cron AutoSnapshot] Error:", error);
    return res.status(500).json({ error: error.message });
  }
}
